### ISSUE TITLE
Síntesis - Diego Alexis Carlos Cruz

### ISSUE THREAD

**Issue by DiegoSCP117** [SistemasTecTlaxiaco/actividad-3-sintesis-DiegoSCP117#2]
[Síntesis - Diego Alexis Carlos Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-DiegoSCP117/files/12515936/Sintesis.-.Diego.Alexis.Carlos.Cruz.pdf)

**Comment by MariaJose-1007** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
